### ISSUE TITLE
Why return the *function* value when maxIter fails to converge to tolerance?

### ISSUE THREAD

**Issue by fasiha** [scijs/minimize-golden-section-1d#2]
I was minimizing a function of `Date`s using this fine library, with just `lowerBound` and `upperBound` and *without* specifying `tolerance`/`maxIter`, and was surprised to see *function* values instead of argument values as output, till I read in the docs that,

> If tolerance is not met, returns best answer.

(This is what triggered my #1… 😅)

This is such a surprising behavior for when the tolerance is not met, I almost think that it'd be better to throw an error in this situation rather than return the *function's value*?

Just a suggestion. Now I've made my tolerance 1e3 (since my function operates on milliseconds since Unix epoch) and am getting perfect results, hooray!

**Comment by jaspervdg** [comment]
Having taken a quick look at the code, I suspect the intention was to
return an "argument", and it's just a bug.

**Comment by rreusser** [comment]
You're right! That makes precisely _no sense at all_. Gosh, it's painful to read old code.

What do you think about an optional `status` argument, e.g. `minimize(f, options, status)`. After completion, it'll have, maybe:

```javascript
status = {value: minimizedValue, iterations: ##, converged: true|false}`
```

That way you can get lazy and just use it inline (`argmin = minimize(f)`), and if you want to be careful about convergence, there's no overloading of outputs or try/catch (is try/catch still the optimization killer it's traditionally been?). I suppose it'd either return either the best guess or NaN (probably NaN?) if it fails to converge.

Edit: Ah, and if you return `NaN`, then you can still return the best guess via the status, just in case that's useful information…

**Comment by fasiha** [comment]
Fixed by https://github.com/scijs/minimize-golden-section-1d/pull/4!
